# Generated by Django 3.1.1 on 2020-09-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=200)),
                ('rollno', models.CharField(max_length=12)),
                ('event', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('cert', models.FileField(upload_to='<django.db.models.fields.CharField>/<django.db.models.fields.CharField>/')),
            ],
        ),
    ]
