# Generated by Django 3.1.1 on 2020-09-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cert_id', models.CharField(max_length=200)),
                ('rollno', models.CharField(max_length=12)),
                ('event', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100, null=True)),
                ('file', models.FileField(null=True, upload_to='certificates/')),
                ('date', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
