# Generated by Django 3.1.1 on 2020-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
