# Generated by Django 3.1.1 on 2020-09-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='id',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cert_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
