# Generated by Django 3.1.1 on 2021-01-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201220_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcert',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tempcert',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
