# Generated by Django 3.1.1 on 2021-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210106_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
