# Generated by Django 3.1.7 on 2022-06-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='institute_name',
            field=models.CharField(default='IIIT Vadodara', max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='year',
            field=models.CharField(max_length=7),
        ),
    ]
