# Generated by Django 3.1.1 on 2021-02-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='expiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='logintoken',
            name='token',
            field=models.CharField(default='xyz', max_length=255),
        ),
    ]
