# Generated by Django 3.1.1 on 2021-02-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210210_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintoken',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
